env:
  node: true
  commonjs: true
  es6: true
  browser: true
  jest: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: tsconfig.json

plugins:
  - "@typescript-eslint"

rules:
  indent:
    - error
    - 2

  linebreak-style:
    - error
    - windows

  quotes:
    - error
    - single

  comma-dangle:
    - error
    - always-multiline

  no-multiple-empty-lines:
    - error
    - max: 1
      maxBOF: 0
      maxEOF: 0

  object-shorthand: error
  no-useless-rename: error

  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/explicit-function-return-type": "off"

  semi: "off"
  "@typescript-eslint/semi":
    - error
    - always

  "@typescript-eslint/ban-types": "off"
  "@typescript-eslint/no-unsafe-return": "off"
