version: 2.1

orbs:
  codecov: codecov/codecov@4.1.0

executors:
  executor_node_18:
    docker:
      - image: cimg/node:18.20.4
    working_directory: ~/build-function

commands:
  command_save_workspace:
    steps:
      - persist_to_workspace:
          root: ~/build-function
          paths:
            - .

  command_restore_workspace:
    steps:
      - attach_workspace:
          at: ~/build-function

  command_publish_to_npm:
    steps:
      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to npm
          command: npm publish

jobs:
  job_checkout_lint:
    executor: executor_node_18
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-build-function-{{ checksum "package-lock.json" }}
            - v2-deps-build-function-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-deps-build-function-{{ checksum "package-lock.json" }}
      - run:
          name: Lint
          command: npm run lint
      - command_save_workspace

  job_ci:
    executor: executor_node_18
    steps:
      - command_restore_workspace
      - run:
          name: Test
          command: npm test
      - run:
          name: Build
          command: npm run build
      - command_save_workspace

  job_upload_coverage:
    executor: executor_node_18
    steps:
      - command_restore_workspace
      - codecov/upload:
          file: coverage/*.json

  job_publish_to_npm:
    executor: executor_node_18
    steps:
      - command_restore_workspace
      - command_publish_to_npm

workflows:
  workflow_ci:
    jobs:
      - job_checkout_lint:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - job_ci:
          requires:
            - job_checkout_lint
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - job_upload_coverage:
          requires:
            - job_ci
          filters:
            branches:
              only: /main/

      - job_publish_to_npm:
          context: npm
          requires:
            - job_ci
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
