version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

executors:

  node:
    docker:
      - image: circleci/node:10
    working_directory: &working_directory ~/build-function

commands:

  npm_publish:
    steps:
      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to npm
          command: npm publish

jobs:

  unit_test:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-build-function-{{ checksum "package.json" }}
            - v1-deps-build-function-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-deps-build-function-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm test
      - persist_to_workspace:
          root: *working_directory
          paths: .

  upload_coverage:
    executor: node
    steps:
      - attach_workspace: &attach_workspace
          at: *working_directory
      - codecov/upload:
          file: coverage/*.json

  build_and_publish:
    executor: node
    steps:
      - attach_workspace: *attach_workspace
      - run:
          name: Build
          command: npm run build
      - npm_publish

workflows:
  version: 2

  workflow:
    jobs:

      - unit_test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - upload_coverage:
          requires:
            - unit_test
          filters:
            branches:
              only: /master/

      - build_and_publish:
          context: npm
          requires:
            - unit_test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
